### ISSUE TITLE
项目根目录生成一堆无用文件

### ISSUE THREAD

**Issue by DuShuYuan** [jarryleo/SingleClick#5]
每次运行都会在项目根目录生成无用的类似log日志的文件  文件名：ajcore.20200323.150613.507.txt
怎么解决？

**Comment by DuShuYuan** [comment]
好像是错误日志文件
`---- AspectJ Properties ---
AspectJ Compiler 1.8.9 built on Monday Mar 14, 2016 at 21:18:16 GMT
---- Dump Properties ---
Dump file: ajcore.20200402.094817.445.txt
Dump reason: java.lang.IllegalStateException
Dump on exception: true
Dump at exit condition: abort
---- Exception Information ---
java.lang.IllegalStateException: Expecting .,<, or ;, but found authapi while unpacking <R::Lcom/google/android/gms/common/api/Result;>Lcom/google/android/gms/common/api/internal/BaseImplementation$ApiMethodImpl<TR;Lcom/google/android/gms/internal/auth-api/zzr;>;
	at org.aspectj.util.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:204)
	at org.aspectj.util.GenericSignatureParser.parseFieldTypeSignature(GenericSignatureParser.java:155)
	at org.aspectj.util.GenericSignatureParser.parseTypeArgument(GenericSignatureParser.java:267)
	at org.aspectj.util.GenericSignatureParser.maybeParseTypeArguments(GenericSignatureParser.java:275)
	at org.aspectj.util.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:196)
	at org.aspectj.util.GenericSignatureParser.parseAsClassSignature(GenericSignatureParser.java:56)
	at org.aspectj.weaver.UnresolvedType.forGenericTypeSignature(UnresolvedType.java:274)
	at org.aspectj.weaver.bcel.BcelWorld.addSourceObjectType(BcelWorld.java:479)
	at org.aspectj.weaver.bcel.BcelWorld.addSourceObjectType(BcelWorld.java:453)
	at org.aspectj.weaver.bcel.BcelWeaver.addAspectsFromJarFile(BcelWeaver.java:263)
	at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:236)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:874)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:249)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:185)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at org.aspectj.tools.ajc.Main$run.call(Unknown Source)`

应该是和google包冲突？？请问怎么解决

**Comment by DuShuYuan** [comment]
classpath 'cn.leo.plugin:magic-plugin:1.0.0'
apply plugin: 'cn.leo.plugin.magic'

as 3.6.2

**Comment by DuShuYuan** [comment]
更换aspectjx插件解决
